### ISSUE TITLE
Allow control of nullability for argument types

### ISSUE THREAD

**Issue by Bastiantheone** [opendoor/pggen#186]
Same as https://github.com/opendoor/pggen/issues/20 but I would also like support for statements not just queries

**Comment by ethanpailes** [comment]
I can take a crack at this, though I'm not sure how fast I'll be.

**Comment by ethanpailes** [comment]
@Bastiantheone I just pushed v0.3.3 that contains this fix if you want to pick it up by updating bazel configs and whatnot.
